# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Generate new localized screenshots"
  lane :screenshots do
    capture_screenshots(scheme: "ImageScannerKit")
  end

  desc "Build xcframework"
  lane :build_xcframework do

    puts 'Clean working directory'
    sh 'cd .. && rm -rf xcframeworks && mkdir xcframeworks'

    puts 'Create XCFramework'
    sh 'cd .. && chmod +x build_xcframework.sh && ./build_xcframework.sh'

  end

end
